const fixedDefaults=['7:00 起床','送孩子上学','到店开始工作','完成今日核心工作','20 分钟散步','阅读 1 小时','控制短视频时间','23:30 睡觉'];
const programs={life:{name:'生活程序',description:'处理日常生活，让生活归位。',duty:'维护日常秩序、环境与基础生活。',rule:'物归论',text:'物有其位，事有其序。做完之后归位。'},work:{name:'工作程序',description:'把今天最重要的工作做好，形成稳定产出。',duty:'创造收入、完成工作责任、维护职业能力。',rule:'砍柴论',text:'只看眼前这一斧。当前程序就是当前世界。'},learning:{name:'学习成长程序',description:'持续积累知识、能力与判断力。',duty:'输入知识、训练能力、形成判断与认知升级。',rule:'积累论',text:'不求一日之功，只求持续积累。'},education:{name:'教育程序',description:'陪伴孩子成长，完成父母应该承担的责任。',duty:'陪伴、教育、示范，为孩子提供稳定成长环境。',rule:'相处论',text:'关系不是管理，而是相处。'},body:{name:'身体健康程序',description:'维护身体这个长期运行的基础系统。',duty:'睡眠、运动、饮食与身体维护。',rule:'复利论',text:'小行动长期重复，最终形成复利。'},finance:{name:'财务程序',description:'管理收入、支出、债务与资产。',duty:'守住现金流，降低风险，逐步改善财务结构。',rule:'绝对论',text:'原则要坚定，具体方法根据现实调整。'},relationship:{name:'关系程序',description:'维护家庭、亲友与重要关系。',duty:'经营重要关系，保持边界、责任与连接。',rule:'相处论',text:'关系不是管理，而是相处。'},environment:{name:'环境程序',description:'管理空间、物品、设备与数字环境。',duty:'让物品归位、环境清晰，减少无意义摩擦。',rule:'物归论',text:'物有其位，事有其序。'},recreation:{name:'休息娱乐程序',description:'有边界地休息、娱乐与恢复。',duty:'恢复精力，而不是让娱乐反过来吞噬生活。',rule:'容错论',text:'允许休息与放松，但必须有边界。'}};
const principles=[['洗衣论','行动优先','先处理眼前该做的事，停止无效思考。'],['砍柴论','专注当前程序','执行时只处理当前这一件事。'],['拔刀论','清除阻碍','凡是拖慢执行的东西，能删就删。'],['相处论','关系需要相处','不把重要关系变成任务管理。'],['物归论','秩序归位','物归其位，事归其序。'],['绝对论','保持边界','原则要坚定，方法要允许调整。'],['积累论','持续积累','能力来自长期重复的小进步。'],['复利论','长期主义','正确的小行动持续重复，会产生复利。'],['容错论','允许失败','系统不是要求完美，而是允许修正后继续。'],['万事归位论','总纲','每件事进入自己的位置，每个程序履行自己的职责。']];
let currentProgram='life',currentDays=7;const today=new Date(),dateKey=toDateKey(today),key='life-os-v04-'+dateKey,historyKey='life-os-history-v04';const saved=JSON.parse(localStorage.getItem(key)||'{}');saved.fixed??=fixedDefaults.map(text=>({text,done:false,program:'life'}));saved.extra??=[];saved.metrics??={};const history=JSON.parse(localStorage.getItem(historyKey)||'{}');const fixedEl=document.querySelector('#fixedTasks'),extraEl=document.querySelector('#extraTasks');
function toDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function getRecord(d){return history[toDateKey(d)]||null}
function save(){localStorage.setItem(key,JSON.stringify(saved));const all=[...saved.fixed,...saved.extra],done=all.filter(t=>t.done).length;history[dateKey]={completed:done,total:all.length,rate:all.length?Math.round(done/all.length*100):0,metrics:{...saved.metrics}};localStorage.setItem(historyKey,JSON.stringify(history))}
function createTaskRow(t,extra){const row=document.createElement('div');row.className='task'+(t.done?' done':'');const c=document.createElement('input');c.type='checkbox';c.checked=t.done;c.onchange=()=>{t.done=c.checked;save();renderTasks()};const text=document.createElement('span');text.textContent=t.text;const actions=document.createElement('div');actions.className='task-actions';const edit=document.createElement('button');edit.className='icon-button';edit.textContent='编辑';edit.onclick=()=>{const n=prompt('修改任务：',t.text);if(n?.trim()){t.text=n.trim();save();renderTasks()}};actions.append(edit);if(extra){const del=document.createElement('button');del.className='icon-button danger';del.textContent='删除';del.onclick=()=>{saved.extra.splice(saved.extra.indexOf(t),1);save();renderTasks()};actions.append(del)}row.append(c,text,actions);return row}
function renderTasks(){fixedEl.innerHTML='';extraEl.innerHTML='';saved.fixed.filter(t=>t.program===currentProgram).forEach(t=>fixedEl.appendChild(createTaskRow(t,false)));saved.extra.filter(t=>t.program===currentProgram).forEach(t=>extraEl.appendChild(createTaskRow(t,true)));updateRate();renderHistory();renderDashboard(currentDays);updateProgramUI()}
function updateRate(){const all=[...saved.fixed,...saved.extra],done=all.filter(t=>t.done).length,rate=all.length?Math.round(done/all.length*100):0;document.querySelector('#rate').textContent=rate+'%';document.querySelector('#completedCount').textContent=`${done}/${all.length}`;document.querySelector('#progressBar').style.width=rate+'%';document.querySelector('#streak').textContent=calculateStreak();const p=all.filter(t=>t.program===currentProgram);document.querySelector('#programCompleted').textContent=p.filter(t=>t.done).length+'/'+p.length}
function calculateStreak(){let s=0,d=new Date(today);while(true){const r=getRecord(d);if(!r||r.rate<100)break;s++;d.setDate(d.getDate()-1)}return s}
function renderHistory(){const el=document.querySelector('#historyList');el.innerHTML='';for(let i=0;i<7;i++){const d=new Date(today);d.setDate(today.getDate()-i);const r=getRecord(d),row=document.createElement('div');row.className='history-row';row.innerHTML=`<span>${i?' '+(d.getMonth()+1)+'/'+d.getDate():'今天'}</span><strong>${r?r.rate+'%':'—'}</strong><small>${r?r.completed+'/'+r.total:'未记录'}</small>`;el.append(row)}}
function collectRecords(days){const a=[];for(let i=days-1;i>=0;i--){const d=new Date(today);d.setDate(today.getDate()-i);a.push({date:d,record:getRecord(d)})}return a}function average(v){v=v.filter(Number.isFinite);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null}
function renderDashboard(days){currentDays=days;const rs=collectRecords(days),rates=rs.map(x=>x.record?.rate).filter(Number.isFinite),read=rs.map(x=>Number(x.record?.metrics?.reading)).filter(Number.isFinite),phone=rs.map(x=>Number(x.record?.metrics?.phone)).filter(Number.isFinite),sleep=rs.map(x=>Number(x.record?.metrics?.sleep)).filter(Number.isFinite);document.querySelector('#summaryRange').textContent=`最近 ${days} 天`;const set=(id,v,s='')=>document.querySelector('#'+id).textContent=v===null?'—':Math.round(v)+(s||'');set('avgRate',average(rates),'%');document.querySelector('#avgReading').textContent=average(read)===null?'—':average(read).toFixed(1)+'h';document.querySelector('#avgPhone').textContent=average(phone)===null?'—':average(phone).toFixed(1)+'h';document.querySelector('#avgSleep').textContent=average(sleep)===null?'—':average(sleep).toFixed(1)+'h';const chart=document.querySelector('#trendChart');chart.innerHTML='';rs.forEach(({date,record})=>{const col=document.createElement('div');col.className='chart-column';const bar=document.createElement('div');bar.className='chart-bar';bar.style.height=`${record?Math.max(record.rate,4):4}%`;bar.title=record?`${toDateKey(date)}：${record.rate}%`:'未记录';const lab=document.createElement('small');lab.textContent=days<=7?date.getMonth()+1+'/'+date.getDate():date.getDate();col.append(bar,lab);chart.append(col)})}
function updateProgramUI(){const p=programs[currentProgram];document.querySelector('#programTitle').textContent=p.name;document.querySelector('#programDescription').textContent=p.description;document.querySelector('#programDuty').textContent=p.duty;document.querySelector('#ruleTitle').textContent=p.rule;document.querySelector('#ruleText').textContent=p.text;document.querySelector('#taskTitle').textContent=p.name+' · 今日任务';document.querySelectorAll('.program-tab').forEach(b=>b.classList.toggle('active',b.dataset.program===currentProgram));document.querySelectorAll('.program-map-item').forEach(b=>b.classList.toggle('active',b.dataset.program===currentProgram))}
function renderProgramNav(){const nav=document.querySelector('#programNav');nav.innerHTML='';Object.entries(programs).forEach(([id,p])=>{const b=document.createElement('button');b.className='program-tab';b.dataset.program=id;b.textContent=p.name;b.onclick=()=>{currentProgram=id;renderTasks()};nav.append(b)})}
function renderProgramMap(){const el=document.querySelector('#programMap');el.innerHTML='';Object.entries(programs).forEach(([id,p],i)=>{const card=document.createElement('button');card.className='program-map-item';card.dataset.program=id;card.innerHTML=`<b>${i+1}. ${p.name}</b><span>${p.duty}</span>`;card.onclick=()=>{currentProgram=id;renderTasks()};el.append(card)})}
function renderPrinciples(){const el=document.querySelector('#principleGrid');el.innerHTML='';principles.forEach((p,i)=>{const card=document.createElement('button');card.className='principle-item';card.innerHTML=`<b>${i+1}. ${p[0]}</b><span>${p[1]}</span>`;card.title=p[2];card.onclick=()=>{document.querySelector('#ruleTitle').textContent=p[0];document.querySelector('#ruleText').textContent=p[2]};el.append(card)})}
document.querySelector('#addTask').onclick=()=>{if(saved.extra.length>=8)return alert('额外任务最多 8 项。');const t=prompt('输入额外任务：');if(t?.trim()){saved.extra.push({text:t.trim(),done:false,program:currentProgram});save();renderTasks()}};
['thinking','indulgence','reading','phone','sleep'].forEach(id=>{const i=document.querySelector('#'+id);i.value=saved.metrics[id]??'';i.oninput=()=>{saved.metrics[id]=i.value;save();renderHistory();renderDashboard(currentDays)}});
document.querySelectorAll('.range').forEach(b=>b.onclick=()=>{document.querySelectorAll('.range').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDashboard(+b.dataset.days)});
document.querySelector('#resetToday').onclick=()=>{if(confirm('确定清空今天所有任务完成状态和额外任务吗？')){saved.fixed=fixedDefaults.map(text=>({text,done:false,program:'life'}));saved.extra=[];saved.metrics={};save();['thinking','indulgence','reading','phone','sleep'].forEach(id=>document.querySelector('#'+id).value='');renderTasks()}};
document.querySelector('#date').textContent=new Intl.DateTimeFormat('zh-CN',{dateStyle:'full'}).format(today);renderProgramNav();renderProgramMap();renderPrinciples();renderTasks();save();