const cockpitProgramRules={life:'物归论',work:'砍柴论',learning:'积累论',education:'相处论',body:'复利论',finance:'绝对论',relationship:'相处论',environment:'物归论',recreation:'容错论'};
const cockpitSchedule=[{start:7,end:8,id:'life',label:'生活启动'},{start:8,end:15,id:'work',label:'工作核心时段'},{start:15,end:17,id:'learning',label:'学习成长'},{start:17,end:20,id:'education',label:'教育与家庭'},{start:20,end:22,id:'recreation',label:'休息娱乐'},{start:22,end:24,id:'body',label:'身体与收尾'},{start:0,end:7,id:'life',label:'生活与睡眠'}];
let cockpitPaused=false,cockpitExecuting=false,cockpitProgramOverride=false;
function cockpitCurrentProgram(){return document.querySelector('.program-tab.active')?.dataset.program||'life'}
function cockpitSelectProgram(id){const b=document.querySelector(`.program-tab[data-program="${id}"]`);if(b)b.click()}
function cockpitScheduled(){const h=new Date().getHours();return cockpitSchedule.find(x=>h>=x.start&&h<x.end)||cockpitSchedule[0]}
function cockpitProgramTasks(id){const fixed=[...document.querySelectorAll('#fixedTasks .task')];const extra=[...document.querySelectorAll('#extraTasks .task')];return [...fixed,...extra].filter(x=>!x.classList.contains('done')).map(x=>({el:x,text:x.querySelector('span')?.textContent||''}))}
function cockpitCurrentTask(){const current=cockpitProgramTasks(cockpitCurrentProgram());if(current.length)return current[0];const scheduled=cockpitScheduled();if(cockpitCurrentProgram()!==scheduled.id){const scheduledTasks=cockpitProgramTasks(scheduled.id);if(scheduledTasks.length){cockpitSelectProgram(scheduled.id);return cockpitProgramTasks(scheduled.id)[0]||null}}for(const tab of document.querySelectorAll('.program-tab')){const id=tab.dataset.program;if(id===cockpitCurrentProgram())continue;const tasks=cockpitProgramTasks(id);if(tasks.length){cockpitSelectProgram(id);return cockpitProgramTasks(id)[0]||null}}return null}
function cockpitRefresh(){const scheduled=cockpitScheduled(),program=cockpitCurrentProgram(),task=cockpitCurrentTask(),active=document.querySelector('.program-tab.active'),name=active?.textContent||'生活程序',rule=cockpitProgramRules[program]||'洗衣论';document.querySelector('#cockpitProgram').textContent=name;document.querySelector('#cockpitRule').textContent=rule;document.querySelector('#cockpitWindow').textContent=scheduled.label;document.querySelector('#cockpitTask').textContent=task?.text||'今日任务已全部完成';document.querySelector('#cockpitStatus').textContent=cockpitExecuting?'执行中':cockpitPaused?'已暂停':task?'等待执行':'今日完成';document.querySelector('#cockpitAction').disabled=!task||cockpitPaused;document.querySelector('#cockpitAction').textContent=cockpitExecuting?'完成':cockpitPaused?'继续':task?'开始执行':'今日完成';document.querySelector('#cockpitPause').textContent=cockpitPaused?'继续':'暂停';document.querySelector('#cockpitPause').disabled=!task||cockpitExecuting;document.querySelector('#cockpitPanel').classList.toggle('paused',cockpitPaused)}
function cockpitComplete(){const task=cockpitCurrentTask();if(!task)return;const checkbox=task.el.querySelector('input[type="checkbox"]');if(checkbox){checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}))}cockpitExecuting=false;cockpitPaused=false;setTimeout(cockpitRefresh,30)}
function cockpitBuild(){const header=document.querySelector('.header');if(!header)return;const panel=document.createElement('section');panel.id='cockpitPanel';panel.className='cockpit card';panel.innerHTML=`<div class="cockpit-head"><div><p class="eyebrow">TODAY / COCKPIT</p><h2>现在做什么</h2><p class="cockpit-sub">系统只给出一个当前行动。时间决定程序，任务状态决定下一步。</p></div><div class="cockpit-status"><span id="cockpitStatus">等待执行</span></div></div><div class="cockpit-grid"><div><span class="cockpit-label">当前程序</span><strong id="cockpitProgram">生活程序</strong></div><div><span class="cockpit-label">当前原则</span><strong id="cockpitRule">物归论</strong></div><div><span class="cockpit-label">当前时段</span><strong id="cockpitWindow">生活启动</strong></div><div class="cockpit-task"><span class="cockpit-label">唯一行动</span><strong id="cockpitTask">—</strong></div></div><div class="cockpit-actions"><button id="cockpitAction">开始执行</button><button id="cockpitPause" class="secondary">暂停</button><button id="cockpitReturn" class="secondary">返回驾驶舱</button></div>`;header.insertAdjacentElement('afterend',panel);
const action=document.querySelector('#cockpitAction');action.onclick=()=>{if(cockpitExecuting){cockpitComplete();return}const task=cockpitCurrentTask();if(!task)return;if(cockpitPaused){cockpitPaused=false;cockpitRefresh();return}cockpitExecuting=true;task.el.scrollIntoView({behavior:'smooth',block:'center'});task.el.classList.add('focus-task');setTimeout(()=>task.el.classList.remove('focus-task'),800);cockpitRefresh()};
document.querySelector('#cockpitPause').onclick=()=>{if(cockpitExecuting)return;cockpitPaused=!cockpitPaused;cockpitRefresh()};document.querySelector('#cockpitReturn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.program-tab').forEach(b=>b.addEventListener('click',()=>{cockpitProgramOverride=true;setTimeout(cockpitRefresh,30)}));document.querySelectorAll('#fixedTasks,#extraTasks').forEach(el=>new MutationObserver(()=>setTimeout(cockpitRefresh,0)).observe(el,{childList:true,subtree:true,attributes:true,attributeFilter:['class']}));cockpitRefresh()}
(function(){const scheduled=cockpitScheduled();cockpitSelectProgram(scheduled.id);cockpitBuild()})();
