const cockpitProgramRules={life:'物归论',work:'砍柴论',learning:'积累论',education:'相处论',body:'复利论',finance:'绝对论',relationship:'相处论',environment:'物归论',recreation:'容错论'};
const cockpitSchedule=[{start:7,end:8,id:'life'},{start:8,end:15,id:'work'},{start:15,end:17,id:'learning'},{start:17,end:20,id:'education'},{start:20,end:22,id:'recreation'},{start:22,end:24,id:'body'},{start:0,end:7,id:'life'}];
let cockpitPaused=false;
function cockpitCurrentProgram(){return document.querySelector('.program-tab.active')?.dataset.program||'life'}
function cockpitSelectProgram(id){const b=document.querySelector(`.program-tab[data-program="${id}"]`);if(b)b.click()}
function cockpitScheduledProgram(){const h=new Date().getHours();return cockpitSchedule.find(x=>h>=x.start&&h<x.end)?.id||'life'}
function cockpitTasks(){return [...document.querySelectorAll('#fixedTasks .task'),...document.querySelectorAll('#extraTasks .task')].filter(x=>!x.classList.contains('done'))}
function cockpitCurrentTask(){const tasks=cockpitTasks();return tasks[0]||null}
function cockpitRefresh(){const program=cockpitCurrentProgram(),task=cockpitCurrentTask();const active=document.querySelector('.program-tab.active');const name=active?.textContent||'生活程序';const rule=cockpitProgramRules[program]||'洗衣论';document.querySelector('#cockpitProgram').textContent=name;document.querySelector('#cockpitRule').textContent=rule;const taskText=task?.querySelector('span')?.textContent||'今日任务已全部完成';document.querySelector('#cockpitTask').textContent=taskText;document.querySelector('#cockpitStatus').textContent=task?'等待执行':'已完成';document.querySelector('#cockpitAction').disabled=!task||cockpitPaused;document.querySelector('#cockpitAction').textContent=cockpitPaused?'已暂停':task?'开始执行':'今日完成';document.querySelector('#cockpitPause').textContent=cockpitPaused?'继续':'暂停';document.querySelector('#cockpitPause').disabled=!task;document.querySelector('#cockpitPanel').classList.toggle('paused',cockpitPaused)}
function cockpitComplete(){const task=cockpitCurrentTask();if(!task)return;const checkbox=task.querySelector('input[type="checkbox"]');if(checkbox){checkbox.checked=true;checkbox.dispatchEvent(new Event('change',{bubbles:true}))}cockpitPaused=false;setTimeout(cockpitRefresh,30)}
function cockpitBuild(){const header=document.querySelector('.header');if(!header)return;const panel=document.createElement('section');panel.id='cockpitPanel';panel.className='cockpit card';panel.innerHTML=`<div class="cockpit-head"><div><p class="eyebrow">TODAY / COCKPIT</p><h2>现在做什么</h2><p class="cockpit-sub">一次只执行一个行动，不在执行中重新规划。</p></div><div class="cockpit-status"><span id="cockpitStatus">等待执行</span></div></div><div class="cockpit-grid"><div><span class="cockpit-label">当前程序</span><strong id="cockpitProgram">生活程序</strong></div><div><span class="cockpit-label">当前原则</span><strong id="cockpitRule">物归论</strong></div><div class="cockpit-task"><span class="cockpit-label">唯一行动</span><strong id="cockpitTask">—</strong></div></div><div class="cockpit-actions"><button id="cockpitAction">开始执行</button><button id="cockpitPause" class="secondary">暂停</button><button id="cockpitReturn" class="secondary">返回驾驶舱</button></div>`;header.insertAdjacentElement('afterend',panel);document.querySelector('#cockpitAction').onclick=()=>{const task=cockpitCurrentTask();if(!task)return;if(cockpitPaused){cockpitPaused=false;cockpitRefresh();return}const button=task.querySelector('.icon-button');task.scrollIntoView({behavior:'smooth',block:'center'});task.classList.add('focus-task');setTimeout(()=>task.classList.remove('focus-task'),800);document.querySelector('#cockpitStatus').textContent='执行中';document.querySelector('#cockpitAction').textContent='完成';document.querySelector('#cockpitAction').onclick=cockpitComplete};document.querySelector('#cockpitPause').onclick=()=>{cockpitPaused=!cockpitPaused;cockpitRefresh()};document.querySelector('#cockpitReturn').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.program-tab').forEach(b=>b.addEventListener('click',()=>setTimeout(cockpitRefresh,30)));document.querySelectorAll('#fixedTasks,#extraTasks').forEach(el=>new MutationObserver(()=>cockpitRefresh()).observe(el,{childList:true,subtree:true,attributes:true,attributeFilter:['class']}));cockpitRefresh()}
(function(){const scheduled=cockpitScheduledProgram();cockpitSelectProgram(scheduled);cockpitBuild()})();
